//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UapkiNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UapkiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UapkiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UapkiNet.UapkiResources", typeof(UapkiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базові обмеження.
        /// </summary>
        internal static string BasicConstraints {
            get {
                return ResourceManager.GetString("BasicConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Політики сертифікату.
        /// </summary>
        internal static string CertificatePolicies {
            get {
                return ResourceManager.GetString("CertificatePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точки доступу до повних СВС.
        /// </summary>
        internal static string CRLDistributionPoints {
            get {
                return ResourceManager.GetString("CRLDistributionPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підпис СВС.
        /// </summary>
        internal static string CrlSign {
            get {
                return ResourceManager.GetString("CrlSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шифрування даних.
        /// </summary>
        internal static string DataEncipherment {
            get {
                return ResourceManager.GetString("DataEncipherment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тільки розшифрування.
        /// </summary>
        internal static string DecipherOnly {
            get {
                return ResourceManager.GetString("DecipherOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підпис.
        /// </summary>
        internal static string DigitalSignature {
            get {
                return ResourceManager.GetString("DigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тільки зашифрування.
        /// </summary>
        internal static string EncipherOnly {
            get {
                return ResourceManager.GetString("EncipherOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точки доступу до часткових СВС.
        /// </summary>
        internal static string FreshestCRL {
            get {
                return ResourceManager.GetString("FreshestCRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видавець (ЦСК).
        /// </summary>
        internal static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ідентифікатор ключа ЦСК.
        /// </summary>
        internal static string IssuerKeyId {
            get {
                return ResourceManager.GetString("IssuerKeyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узгодження ключів.
        /// </summary>
        internal static string KeyAgreement {
            get {
                return ResourceManager.GetString("KeyAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДСТУ 4145.
        /// </summary>
        internal static string KeyAlgo_Dstu4145 {
            get {
                return ResourceManager.GetString("KeyAlgo_Dstu4145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECDSA.
        /// </summary>
        internal static string KeyAlgo_Ecdsa {
            get {
                return ResourceManager.GetString("KeyAlgo_Ecdsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA.
        /// </summary>
        internal static string KeyAlgo_Rsa {
            get {
                return ResourceManager.GetString("KeyAlgo_Rsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не підтримується.
        /// </summary>
        internal static string KeyAlgo_Unsupported {
            get {
                return ResourceManager.GetString("KeyAlgo_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підпис сертифікатів.
        /// </summary>
        internal static string KeyCertSign {
            get {
                return ResourceManager.GetString("KeyCertSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шифрування ключів.
        /// </summary>
        internal static string KeyEncipherment {
            get {
                return ResourceManager.GetString("KeyEncipherment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕК 233 біт.
        /// </summary>
        internal static string KeyParameter_M233_PB {
            get {
                return ResourceManager.GetString("KeyParameter_M233_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕК 257 біт.
        /// </summary>
        internal static string KeyParameter_M257_PB {
            get {
                return ResourceManager.GetString("KeyParameter_M257_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕК 307 біт.
        /// </summary>
        internal static string KeyParameter_M307_PB {
            get {
                return ResourceManager.GetString("KeyParameter_M307_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕК 367 біт.
        /// </summary>
        internal static string KeyParameter_M367_PB {
            get {
                return ResourceManager.GetString("KeyParameter_M367_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕК 431 біт.
        /// </summary>
        internal static string KeyParameter_M431_PB {
            get {
                return ResourceManager.GetString("KeyParameter_M431_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕК NIST P-256.
        /// </summary>
        internal static string KeyParameter_P256 {
            get {
                return ResourceManager.GetString("KeyParameter_P256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕК NIST P-384.
        /// </summary>
        internal static string KeyParameter_P384 {
            get {
                return ResourceManager.GetString("KeyParameter_P384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕК NIST P-521.
        /// </summary>
        internal static string KeyParameter_P521 {
            get {
                return ResourceManager.GetString("KeyParameter_P521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1024 біт.
        /// </summary>
        internal static string KeyParameter_RSA1024 {
            get {
                return ResourceManager.GetString("KeyParameter_RSA1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1536 біт.
        /// </summary>
        internal static string KeyParameter_RSA1536 {
            get {
                return ResourceManager.GetString("KeyParameter_RSA1536", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2048 біт.
        /// </summary>
        internal static string KeyParameter_RSA2048 {
            get {
                return ResourceManager.GetString("KeyParameter_RSA2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3072 біт.
        /// </summary>
        internal static string KeyParameter_RSA3072 {
            get {
                return ResourceManager.GetString("KeyParameter_RSA3072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4096 біт.
        /// </summary>
        internal static string KeyParameter_RSA4096 {
            get {
                return ResourceManager.GetString("KeyParameter_RSA4096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не підтримується.
        /// </summary>
        internal static string KeyParameter_Unsupported {
            get {
                return ResourceManager.GetString("KeyParameter_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Використання ключа.
        /// </summary>
        internal static string KeyUsage {
            get {
                return ResourceManager.GetString("KeyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узгодження ключів.
        /// </summary>
        internal static string KeyUsage_KeyAgreement {
            get {
                return ResourceManager.GetString("KeyUsage_KeyAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підпис.
        /// </summary>
        internal static string KeyUsage_Signature {
            get {
                return ResourceManager.GetString("KeyUsage_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неспростовність.
        /// </summary>
        internal static string NonRepudiation {
            get {
                return ResourceManager.GetString("NonRepudiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чинний до.
        /// </summary>
        internal static string NotAfter {
            get {
                return ResourceManager.GetString("NotAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чинний з.
        /// </summary>
        internal static string NotBefore {
            get {
                return ResourceManager.GetString("NotBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмеження на довжину ланцюжка.
        /// </summary>
        internal static string PathLenConstraint {
            get {
                return ResourceManager.GetString("PathLenConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкритий ключ.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметри відкритого ключа.
        /// </summary>
        internal static string PublicKeyParameters {
            get {
                return ResourceManager.GetString("PublicKeyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серійний номер.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алгоритм підпису.
        /// </summary>
        internal static string SignAlgo {
            get {
                return ResourceManager.GetString("SignAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДСТУ 4145 з ГОСТ 34.311 (Застарілий).
        /// </summary>
        internal static string SignAlgo_Dstu4145_Gost34311 {
            get {
                return ResourceManager.GetString("SignAlgo_Dstu4145_Gost34311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДСТУ 4145 з ДСТУ 7564 (Купина-256).
        /// </summary>
        internal static string SignAlgo_Dstu4145_Kupyna256 {
            get {
                return ResourceManager.GetString("SignAlgo_Dstu4145_Kupyna256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДСТУ 4145 з ДСТУ 7564 (Купина-384).
        /// </summary>
        internal static string SignAlgo_Dstu4145_Kupyna384 {
            get {
                return ResourceManager.GetString("SignAlgo_Dstu4145_Kupyna384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДСТУ 4145 з ДСТУ 7564 (Купина-512).
        /// </summary>
        internal static string SignAlgo_Dstu4145_Kupyna512 {
            get {
                return ResourceManager.GetString("SignAlgo_Dstu4145_Kupyna512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECDSA з SHA1.
        /// </summary>
        internal static string SignAlgo_Ecdsa_Sha {
            get {
                return ResourceManager.GetString("SignAlgo_Ecdsa_Sha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECDSA з SHA224.
        /// </summary>
        internal static string SignAlgo_Ecdsa_Sha224 {
            get {
                return ResourceManager.GetString("SignAlgo_Ecdsa_Sha224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECDSA з SHA256.
        /// </summary>
        internal static string SignAlgo_Ecdsa_Sha256 {
            get {
                return ResourceManager.GetString("SignAlgo_Ecdsa_Sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECDSA з SHA384.
        /// </summary>
        internal static string SignAlgo_Ecdsa_Sha384 {
            get {
                return ResourceManager.GetString("SignAlgo_Ecdsa_Sha384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECDSA з SHA512.
        /// </summary>
        internal static string SignAlgo_Ecdsa_Sha512 {
            get {
                return ResourceManager.GetString("SignAlgo_Ecdsa_Sha512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA PKCS#1 v1.5 з SHA1.
        /// </summary>
        internal static string SignAlgo_RsaPkcs_Sha {
            get {
                return ResourceManager.GetString("SignAlgo_RsaPkcs_Sha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA PKCS#1 v1.5 з SHA224.
        /// </summary>
        internal static string SignAlgo_RsaPkcs_Sha224 {
            get {
                return ResourceManager.GetString("SignAlgo_RsaPkcs_Sha224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA PKCS#1 v1.5 з SHA256.
        /// </summary>
        internal static string SignAlgo_RsaPkcs_Sha256 {
            get {
                return ResourceManager.GetString("SignAlgo_RsaPkcs_Sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA PKCS#1 v1.5 з SHA384.
        /// </summary>
        internal static string SignAlgo_RsaPkcs_Sha384 {
            get {
                return ResourceManager.GetString("SignAlgo_RsaPkcs_Sha384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA PKCS#1 v1.5 з SHA512.
        /// </summary>
        internal static string SignAlgo_RsaPkcs_Sha512 {
            get {
                return ResourceManager.GetString("SignAlgo_RsaPkcs_Sha512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA-PSS.
        /// </summary>
        internal static string SignAlgo_RsaPss {
            get {
                return ResourceManager.GetString("SignAlgo_RsaPss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        internal static string SignAlgo_Unsupported {
            get {
                return ResourceManager.GetString("SignAlgo_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З повними даними для перевірки та архівною позначкою часу (CAdES-LTA).
        /// </summary>
        internal static string SignatureFormat_CAdES_A {
            get {
                return ResourceManager.GetString("SignatureFormat_CAdES_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовий (CAdES-BES).
        /// </summary>
        internal static string SignatureFormat_CAdES_BES {
            get {
                return ResourceManager.GetString("SignatureFormat_CAdES_BES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З посиланням на дані для перевірки (CAdES-C).
        /// </summary>
        internal static string SignatureFormat_CAdES_C {
            get {
                return ResourceManager.GetString("SignatureFormat_CAdES_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З позначкою часу від підпису (CAdES-T).
        /// </summary>
        internal static string SignatureFormat_CAdES_T {
            get {
                return ResourceManager.GetString("SignatureFormat_CAdES_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З повними даними для перевірки (CAdES-LT).
        /// </summary>
        internal static string SignatureFormat_CAdES_XL {
            get {
                return ResourceManager.GetString("SignatureFormat_CAdES_XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовий з ідентифікацією підписника за ідентифікатором ключа.
        /// </summary>
        internal static string SignatureFormat_CMS {
            get {
                return ResourceManager.GetString("SignatureFormat_CMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Власник.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ідентифікатор ключа власника.
        /// </summary>
        internal static string SubjectKeyId {
            get {
                return ResourceManager.GetString("SubjectKeyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип власника.
        /// </summary>
        internal static string SubjectType {
            get {
                return ResourceManager.GetString("SubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЦСК.
        /// </summary>
        internal static string SubjectTypeCa {
            get {
                return ResourceManager.GetString("SubjectTypeCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кінцевий користувач.
        /// </summary>
        internal static string SubjectTypeEndEntity {
            get {
                return ResourceManager.GetString("SubjectTypeEndEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версія.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
